# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 20 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Nic Durish
description: "A collection of ramblings and reflections"
timezone: Canada/Eastern
#url: "https://nicdurish.ca"
CNAME: blog.nicdurish.ca
url: "blog.nicdurish.ca"

cover: ./img/banner-8.jpg
logo: #
logo_dark: #
favicon: ./img/favicon.png


# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`

website: nicdurish.ca
email: #
linkedin: nicdurish
twitter: durishn # replace by your username
facebook:  # replace by your username
instagram: nicdurish
youtube: NicDurish
github: Durishn


# Disqus
disqus: false
disqus_shortname: durishn # replace with your disqus username

# Google Analytics
google_analytics: UA-135084842-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:short_year-:month-:day/:title:output_ext
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

